### ISSUE TITLE
Package not found

### ISSUE THREAD

**Issue by seoanalyze** [AndreasGJ/seo-meta-field-nova#1]
If I try to install your package with composer I get the following error:
`  [InvalidArgumentException]                                                   
  Could not find a matching version of package agj/seo-meta-field-nova. Check  
   the package spelling, your version constraint and that the package is avai  
  lable in a stability which matches your minimum-stability (dev).`

**Comment by AndreasGJ** [comment]
I'm having some troubles releasing it correctly. I will get back to you when its setup correctly 👍

**Comment by AndreasGJ** [comment]
@seoanalyze Could you try downloading the package with the following code instead:
`composer require gwd/seo-meta-nova-field`

**Comment by seoanalyze** [comment]
Works fine. Thank you :)
