### ISSUE TITLE
Output is the default from .env only

### ISSUE THREAD

**Issue by golchha21** [AndreasGJ/seo-meta-field-nova#21]
I have made all the setup and the data is even saved.. but when trying to load the information with `@include('seo-meta::seo')` just the default ones from the .env shows.

**Comment by AndreasGJ** [comment]
@golchha21 could you show me the files:

1. The Model you have added the `Gwd\SeoMeta\Traits\SeoMetaTrait` on ?
2. The blade file you have added the `@include('seo-meta::seo')` in?
3. Your `seo.php` config file?

**Comment by golchha21** [comment]
@AndreasGJ Yes all the three steps have been followed.

**Comment by AndreasGJ** [comment]
> @AndreasGJ Yes all the three steps have been followed.
> 
> For now I am passing the model instance `@include('seo-meta::seo', ['page' => $page])`, and this works.

okay, I will update the documentation then :)
